title: baseline

# Build settings

# As of November 2023, GitHub Pages still uses Minima 2.5.1 (https://pages.github.com/versions/). 
# If you want to use the latest Minima version on GitHub Pages, use the following setting and 
# add a line comment on "theme: minima" above.
#remote_theme: jekyll/minima

ios_app_id: 1621132298
url: https://getbaseline.app
tagline: A better journaling and mood tracking app.
description: A better journaling and mood tracking app. 100% free and private. Non-profit owned and operated.
twitter:
  username: getbaselineapp

plugins:
  - jekyll-seo-tag
  - jekyll-toc

# Theme-specific settings

# If you want to link only specific pages in your header, use this and add the path to the pages
# in order as they should show up.
header_pages:
  - index.md

# Set to `true` to show excerpts on the homepage.
#show_excerpts: false

# Minima specific settings, which are only available from Minima 3.0 onward.
minima:
  skin: classic

toc:
  min_level: 2
  max_level: 2

features                                  :

  - title                                 : Understand your brain.
    description                           : Journaling is proven to help people understand themselves and improve their mental health. baseline is designed to make it as easy as possible.
    fontawesome_icon_name                 : pencil

  - title                                 : Recap your week.
    description                           : At the end of each week, you'll get a chance to take some mental health surveys and review your overall mental health.
    fontawesome_icon_name                 : backward

  - title                                 : Track your progress.
    description                           : baseline uses dynamic visualizations to help you better understand how your mood changes over time, along with other metrics like stress and resilience.
    fontawesome_icon_name                 : chart-line

  - title                                 : Keep private thoughts private.
    description                           : You can set a passphrase in-app to hide your data from people who might have access to your device.
    fontawesome_icon_name                 : key

  - title                                 : Make a schedule.
    description                           : Set granular notifications to keep yourself accountable to your mental health goals.
    fontawesome_icon_name                 : calendar-days

  - title                                 : Protect your information.
    description                           : We encrypt your data so that not even we can see it, let alone anyone else.
    fontawesome_icon_name                 : lock
